### ISSUE TITLE
Scrolls to lastPosition if tool panel is open and entering text somewhere else

### ISSUE THREAD

**Issue by dsandstrom** [gangstead/atom-incremental-search#16]
Steps to reproduce:

1. Open panel
2. enter text found on page
3. scroll window down/up
4. enter character

**Comment by gangstead** [comment]
I just inherited the project and bulk closed all the open issues. Allow me to explain my reasoning:

The package has been losing functionality as it stagnates while Atom marches forward. I've been making changes to remove the deprecations before the API 1.0 cutoff on 6/1/15 or else the package will be blocked from loading. Some are fixed, but it's not done yet. I suspect fixing all the Atom API issues will resolve most of the issues I just closed (hopefully without introducing new ones!). Your issue might be fixed by then, if not feel free to reopen/create a new one, but please be patient.

With this first round of deprecation fixes v4.4.0 on Atom 0.204.0 I restored basic open search box and searches advance while you type functionality. Past that it is still throwing some exceptions as a lot of the package needs to be overhauled.

Thanks for your interest in the package. Submitting issues is a big help, that's how I got started. I'm doing this as a labor of love in my spare time and would love to have more contributors.
