### ISSUE TITLE
"Enter" only works on first incremental search

### ISSUE THREAD

**Issue by edsko** [gangstead/atom-incremental-search#24]
(This is on OSX, Atom 0.177.0, incremental-search 4.2.0.)

First time it works fine. ⌘i, type a word, hit enter, end up with that word selected and the incremental search stops. But now when I repeat; ⌘i, type a word (word gets selected), and hit enter, nothing happens -- the search box does not disappear (escape works and gets me back to where I started).

**Comment by moxley** [comment]
+1 for me.

OS X 10.10.2
Atom 0.180.0
incremental-search 4.2.0

**Comment by gangstead** [comment]
I just inherited the project and bulk closed all the open issues. Allow me to explain my reasoning:

The package has been losing functionality as it stagnates while Atom marches forward. I've been making changes to remove the deprecations before the API 1.0 cutoff on 6/1/15 or else the package will be blocked from loading. Some are fixed, but it's not done yet. I suspect fixing all the Atom API issues will resolve most of the issues I just closed (hopefully without introducing new ones!). Your issue might be fixed by then, if not feel free to reopen/create a new one, but please be patient.

With this first round of deprecation fixes v4.4.0 on Atom 0.204.0 I restored basic open search box and searches advance while you type functionality. Past that it is still throwing some exceptions as a lot of the package needs to be overhauled.

Thanks for your interest in the package. Submitting issues is a big help, that's how I got started. I'm doing this as a labor of love in my spare time and would love to have more contributors.
