### ISSUE TITLE
Won't work?

### ISSUE THREAD

**Issue by exalted** [gangstead/atom-incremental-search#26]
Hi,

sorry for such a lazy title, but hopefully here's more insight to it:

* Atom Version `0.184.0 (0.184.0)`
* incremental-search `4.2.0`
* Mac OS X `10.10.2`

Although `cmd-i` will popup the incremental search box below the editor area, when I hit keys on my keyboard nothing will happen (meaning not that it won't actually find anything, but pressed keys won't even appear on the search/find field).

Any ideas?

Thank you.

**Comment by lodestone** [comment]
+1

I am having this same issue. Pretty much all the same stats. OSX 10.10.2, Inc Search 4.2, Atom Vers 0.185...

I don't even know where to begin trying to debug why this is happening.

**Comment by edsko** [comment]
Confirmed. This broke somewhere between Atom 0.182 and 0.184.

**Comment by edsko** [comment]
This seems to be affected other packages as well; see https://github.com/moshee/atom-pipe/issues/7 for instance.

**Comment by jeduan** [comment]
:+1:

**Comment by exalted** [comment]
Weird. I see this package gets updated, but still not working. Is increment search working to some and not to others?

**Comment by nwinkler** [comment]
The search is working for me, but I don't see any of the typed characters in the incremental search text field.

Atom 0.194.0
Incremental Search 4.3.0

**Comment by exalted** [comment]
@gangstead closed, because it’s fixed or not interested or what please?

**Comment by gangstead** [comment]
I just inherited the project and bulk closed all the open issues.  Allow me to explain my reasoning:

The package has been losing functionality as it stagnates while Atom marches forward.  I've been making changes to remove the deprecations before the API 1.0 cutoff on *_6/1/15_* or else the package will be blocked from loading.  Some are fixed, but it's not done yet.  I suspect fixing all the Atom API issues will resolve most of the issues I just closed (hopefully without introducing new ones!).  Your issue might be fixed by then, if not feel free to reopen/create a new one, but please be patient.

With this first round of deprecation fixes `v4.4.0` on `Atom 0.204.0` I restored basic open search box and searches advance while you type functionality.  Past that it is still throwing some exceptions as a lot of the package needs to be overhauled.

Thanks for your interest in the package.  Submitting issues is a big help, that's how I got started.  I'm doing this as a labor of love in my spare time and would love to have more contributors.
