### ISSUE TITLE
0.194: "Failed to load the incremental-search package"

### ISSUE THREAD

**Issue by fburleigh** [gangstead/atom-incremental-search#29]
Atom updated itself to .194, and threw up on three packages, including isearch.  Atom's complaint seems to be:

Cannot read property 'prototype' of undefined

More (automated) info below.

Thanks!

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [incremental-search](https://github.com/mkleehammer/atom-incremental-search) package, v4.3.0

### Stack Trace

Failed to load the incremental-search package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/burleigh/.atom/packages/incremental-search/lib/input-view.coffee:5:199)
    at /Users/burleigh/.atom/packages/incremental-search/lib/input-view.coffee:12:5
    at Object.<anonymous> (/Users/burleigh/.atom/packages/incremental-search/lib/input-view.coffee:252:5)
    at Object.<anonymous> (/Users/burleigh/.atom/packages/incremental-search/lib/input-view.coffee:254:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-plus",
      "linter-tidy",
      "wrap-guide"
    ],
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-xsltransform, v0.1.0
autoclose-html, v0.15.0
block-cursor, v0.12.4
emmet, v2.3.8
git-log, v0.3.0
git-tab-status, v1.7.0
incremental-search, v4.3.0
linter, v0.12.1
linter-jshint, v0.1.2
linter-php, v0.0.12
linter-scss-lint, v0.0.14
linter-xmllint, v0.0.5
open-recent, v2.2.2
pain-split, v1.3.1
project-manager, v1.15.5
regex-railroad-diagram, v0.7.4
remote-edit, v1.7.2
script, v2.19.0

# Dev
No dev packages
```

**Comment by gangstead** [comment]
I just inherited the project and bulk closed all the open issues.  Allow me to explain my reasoning:

The package has been losing functionality as it stagnates while Atom marches forward.  I've been making changes to remove the deprecations before the API 1.0 cutoff on *_6/1/15_* or else the package will be blocked from loading.  Some are fixed, but it's not done yet.  I suspect fixing all the Atom API issues will resolve most of the issues I just closed (hopefully without introducing new ones!).  Your issue might be fixed by then, if not feel free to reopen/create a new one, but please be patient.

With this first round of deprecation fixes `v4.4.0` on `Atom 0.204.0` I restored basic open search box and searches advance while you type functionality.  Past that it is still throwing some exceptions as a lot of the package needs to be overhauled.

Thanks for your interest in the package.  Submitting issues is a big help, that's how I got started.  I'm doing this as a labor of love in my spare time and would love to have more contributors.
